//! Serve the embedded dashboard bundle (Dioxus/WASM — #97, epic #95).
//!
//! The bundle under `../dashboard/` is a build artifact **committed to the
//! repo** and regenerated by `scripts/build-dashboard.sh`. Committing it keeps
//! the "one binary ships the UI" property — an ordinary `cargo build` needs no
//! wasm toolchain — at the cost of a build artifact in git. CI reruns the build
//! and diffs the tree, so a stale bundle fails the build rather than shipping.
//!
//! Assets are looked up in a table generated by `build.rs` (see that file for
//! why the list can't be hardcoded). The page is served at `/` and its files
//! under `/assets/`. It became the default at `/` in #191, briefly aliased at
//! `/v2` because the bundle's own asset URLs were absolute `/v2/...`; #197
//! removed the vanilla-JS page it had been sharing the server with, and the
//! version-suffixed paths went with it — there is only one dashboard now.

use axum::extract::Path;
use axum::http::{StatusCode, header};
use axum::response::{IntoResponse, Response};

include!(concat!(env!("OUT_DIR"), "/dashboard_assets.rs"));

/// Content-Security-Policy for the dashboard page.
///
/// The bundle is fully self-contained — no CDN, font, remote image, or inline
/// handler — so every fetch directive is denied except same-origin.
/// `'wasm-unsafe-eval'` is the one grant WebAssembly instantiation requires;
/// without it the module refuses to start.
pub const CSP: &str = "default-src 'none'; script-src 'self' 'wasm-unsafe-eval'; \
style-src 'self'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; \
form-action 'none'";

/// Look up one bundle file by its path relative to the bundle root.
fn lookup(path: &str) -> Option<(&'static str, &'static [u8])> {
    ASSETS
        .iter()
        .find(|(p, _, _)| *p == path)
        .map(|(_, ct, bytes)| (*ct, *bytes))
}

fn serve(path: &str) -> Response {
    match lookup(path) {
        Some((content_type, bytes)) => {
            ([(header::CONTENT_TYPE, content_type)], bytes).into_response()
        }
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// `GET /` — the dashboard page.
pub async fn index() -> Response {
    match lookup("index.html") {
        Some((content_type, bytes)) => (
            [
                (header::CONTENT_TYPE, content_type),
                (header::CONTENT_SECURITY_POLICY, CSP),
            ],
            bytes,
        )
            .into_response(),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// `GET /assets/{*path}` — any other file in the bundle (JS glue, wasm, CSS,
/// and the wasm-bindgen `snippets/` tree).
///
/// Lookup is an exact match against a static table, so a traversal attempt like
/// `../Cargo.toml` simply misses and 404s — there is no filesystem access here.
pub async fn asset(Path(path): Path<String>) -> Response {
    serve(&path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_bundle_contains_its_entrypoints() {
        for required in [
            "index.html",
            "app.css",
            "prospero-dashboard.js",
            "prospero-dashboard_bg.wasm",
        ] {
            assert!(
                lookup(required).is_some(),
                "bundle is missing {required} — run scripts/build-dashboard.sh"
            );
        }
    }

    #[test]
    fn wasm_is_served_as_application_wasm() {
        // instantiateStreaming rejects every other content type.
        let (ct, bytes) = lookup("prospero-dashboard_bg.wasm").unwrap();
        assert_eq!(ct, "application/wasm");
        assert_eq!(&bytes[..4], b"\0asm", "not a wasm module");
    }

    #[test]
    fn unknown_paths_and_traversal_attempts_miss() {
        assert!(lookup("nope.js").is_none());
        assert!(lookup("../Cargo.toml").is_none());
    }
}
