[book]
title = "prospero"
description = "Orchestration layer for caliban."
authors = ["caliban-ai"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/caliban-ai/prospero"
preferred-dark-theme = "navy"
additional-css = ["theme/caliban-ai.css"]
additional-js = ["theme/nav.js"]

[output.html.search]
enable = true
