//! Generate the Dashboard v2 static-asset table (#97).
//!
//! The wasm bundle under `dashboard-v2/` is not a fixed file list: wasm-bindgen
//! emits per-dependency JS under `snippets/<crate>-<hash>/…`, and those hashes
//! change whenever a dependency does. Hardcoding `include_bytes!` calls would
//! therefore rot silently — the glue would import a snippet the server no longer
//! routes, and the app would fail to boot in the browser.
//!
//! So the table is generated here by walking the directory at build time. Each
//! entry still resolves to an `include_bytes!`, so the bytes are embedded in the
//! binary exactly as before and `cargo` tracks each file for rebuilds. This
//! keeps prosperod's dependency tree lean — no `rust-embed`/`mime_guess` in the
//! server — while staying correct across dependency churn.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let bundle = manifest_dir.join("dashboard-v2");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("dashboard_v2_assets.rs");

    // Rebuild when any bundle file is added, removed, or changed.
    println!("cargo:rerun-if-changed={}", bundle.display());

    let mut files = Vec::new();
    collect(&bundle, &bundle, &mut files);
    files.sort();

    let mut src = String::from(
        "/// Every file in the committed Dashboard v2 bundle, as\n\
         /// `(url_path, content_type, bytes)`. Generated by `build.rs`.\n\
         pub static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        writeln!(
            src,
            "    ({:?}, {:?}, include_bytes!({:?})),",
            rel,
            content_type(rel),
            abs
        )
        .unwrap();
    }
    src.push_str("];\n");

    std::fs::write(&out, src).unwrap();
}

/// Recursively collect `(path_relative_to_root, absolute_path)` for every file.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            // Forward slashes: this is a URL path, not a filesystem path.
            let rel = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path));
        }
    }
}

/// MIME type by extension. `application/wasm` is load-bearing —
/// `WebAssembly.instantiateStreaming` rejects any other type.
fn content_type(path: &str) -> &'static str {
    match path.rsplit_once('.').map(|(_, ext)| ext) {
        Some("html") => "text/html; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("js") | Some("mjs") => "application/javascript; charset=utf-8",
        Some("wasm") => "application/wasm",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("woff2") => "font/woff2",
        _ => "application/octet-stream",
    }
}
